export const INDUSTRIES = [
  "Aerospace & Defense",
  "Agriculture & Forestry",
  "Arts, Entertainment & Recreation",
  "Architecture & Construction",
  "Education",
  "Education - Higher",
  "Financial Services (Banking / Insurance / Multifinance / Fintech)",
  "Government - Federal/National",
  "Government - State/Local",
  "Healthcare",
  "Hospitality",
  "Manufacturing",
  "Media & Advertising",
  "Mining/Oil/Gas",
  "Pharmaceutical",
  "Professional Service",
  "Reseller/Integrator",
  "Retail",
  "Technology",
  "Telecommunication",
  "Transportation & Logistics",
  "Utility",
  "Wholesale/Distributor",
  "Holding Company",
  "Principal",
  "Other"
] as const;

export type Industry = typeof INDUSTRIES[number];
